import assert from 'node:assert/strict'
import { execFileSync } from 'node:child_process'
import { readdirSync, readFileSync, statSync } from 'node:fs'
import { join, relative } from 'node:path'
import { fileURLToPath } from 'node:url'
import test from 'node:test'
import { assembleLogyqEngine, assembleLogyqPreview } from '../scripts/assemble-logyq.mjs'
import { engineSource, logyqDir } from './logyq-source.mjs'

const root = fileURLToPath(new URL('..', import.meta.url))
const indexPath = join(logyqDir, 'index.html')
const previewPath = join(logyqDir, 'js/preview.js')

function walk(dir, files = []) {
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const path = join(dir, entry.name)
    if (entry.isDirectory()) walk(path, files)
    else files.push(path)
  }
  return files
}

test('LOGYQ lives only under public/logyq and does not import v161 asset paths', () => {
  const files = walk(logyqDir).filter((path) => /\.(html|js|css)$/.test(path))
  assert.ok(files.length > 0)
  for (const path of files) {
    const text = readFileSync(path, 'utf8')
    assert.doesNotMatch(text, /\/logiq-v161\//, relative(root, path))
    assert.doesNotMatch(text, /LOGiQBridge/)
    assert.doesNotMatch(text, /logiq-preview\.js/)
    assert.doesNotMatch(text, /\/logyq\/logyq-preview\.js/)
  }
})

test('isolated copy retains the v161 engine markers and working controls', () => {
  const html = readFileSync(indexPath, 'utf8')
  const engine = engineSource()
  const preview = readFileSync(previewPath, 'utf8')

  assert.match(html, /<title>LOGYQ<\/title>/)
  assert.match(engine, /window\.LOGYQBridge = Object\.freeze/)
  assert.match(html, /<script src="\/logyq\/js\/engine\.js"><\/script>/)
  assert.match(html, /<script src="\/logyq\/js\/preview\.js"><\/script>/)
  assert.match(preview, /const bridge = window\.LOGYQBridge/)
  assert.match(preview, /logyq_current_map_v1/)
  assert.match(preview, /logyq_pending_save_v1/)
  assert.doesNotMatch(preview, /logyq_handedness_v1/)
  assert.doesNotMatch(html, /id="logyqHandRight"/)
  assert.doesNotMatch(html, /id="logyqHandLeft"/)
  assert.match(html, /id="logyq-phone-boot"/)
  assert.match(html, /id="logiq-mobile-header"/)
  assert.match(html, /id="logyq-paint-btn"/)
  assert.match(html, /id="logyq-paint-settings-btn"/)
  assert.match(html, /<style id="logyq-phone-boot">[\s\S]*#trash\{display:none!important/)
  const appCss = readFileSync(join(logyqDir, 'css/app.css'), 'utf8')
  assert.match(appCss, /body>header\{display:none!important\}/)
  assert.match(appCss, /#trash\{display:none!important;visibility:hidden!important/)
  assert.doesNotMatch(preview, /logiq_v161_current_map_v1|logiq_v161_pending_save_v1/)
  assert.doesNotMatch(preview, /logiq_lab_pin_v1/)

  for (const marker of [
    'const CONFIG =',
    'const state =',
    'const utils =',
    'const Detectors =',
    'const dragManager =',
    'const treeManager =',
    'function keyDispatcher',
    'function randomizeTree',
    'function undo',
    'function openNodeEditor',
    'function moveSelectedVertically',
    'function moveSelectedHorizontally',
    'function sendSubtreeToWordBank',
    'function deleteNodesToTrash',
  ]) assert.ok(engine.includes(marker), `missing engine marker: ${marker}`)

  for (const id of [
    'wordInput', 'addWordBtn', 'undoBtn', 'mixBtn', 'mapsBtn', 'fitBtn',
    'settingsBtn', 'helpBtn', 'Dock', 'Toast', 'canvas', 'trash',
  ]) assert.match(html, new RegExp(`id=["']${id}["']`), `missing #${id}`)

  assert.doesNotMatch(html, /id=["']saveBtn["']/)
  assert.doesNotMatch(html, /id=["']showCarets["']/)
})

test('LOGYQ persistence, gesture, and Lab-tab docs stay with the copy', () => {
  const persist = readFileSync(join(logyqDir, 'PERSISTENCE.md'), 'utf8')
  const gestures = readFileSync(join(logyqDir, 'GESTURE_STATES.md'), 'utf8')
  const labTab = readFileSync(join(logyqDir, 'LAB_TAB.md'), 'utf8')
  assert.match(persist, /`name`/)
  assert.match(persist, /`color`/)
  assert.match(persist, /`label`, `text`, `title`, `value`/)
  assert.match(persist, /GIQ/)
  assert.match(persist, /formatVersion/)
  assert.match(persist, /logiq_map_list/)
  assert.match(persist, /0 maps/)
  assert.match(persist, /No first-run coaching/)
  assert.match(persist, /Blank drafts do not persist/)
  assert.match(persist, /\*\*not\*\* wrapped as `\{ formatVersion, root \}`/)
  assert.match(gestures, /Idle --> Excited/)
  assert.match(gestures, /1\.1cm/)
  assert.match(labTab, /#logyq-hub-card/)
  assert.match(labTab, /#logiq-v161-hub-card/)
  const hub = readFileSync(join(root, 'index.html'), 'utf8')
  assert.match(hub, /id = 'logiq-v161-hub-card'/)
  assert.match(hub, /id = 'logyq-hub-card'/)
  assert.match(hub, /window\.location\.href = '\/logyq\/'/)
  assert.match(hub, /window\.location\.href = '\/logiq-v161\/'/)
})

test('LOGYQ preview uses live logiq_maps PIN RPCs; engine does not', () => {
  const preview = readFileSync(previewPath, 'utf8')
  const engine = engineSource()
  assert.match(preview, /logyq_lab_pin_v1/)
  assert.match(preview, /logyq_current_map_v1/)
  assert.match(preview, /logyq_pending_save_v1/)
  assert.match(preview, /logyq_maps_v1/)
  assert.match(preview, /logyq_paint_color_v1/)
  assert.match(preview, /jzaghifuhinkzzhiojre\.supabase\.co/)
  assert.match(preview, /MAP_FORMAT_VERSION = 2/)
  assert.match(preview, /function encodeMapTree/)
  assert.match(preview, /function bootSession/)
  assert.match(preview, /function createMap/)
  assert.match(preview, /id="logyq-home-btn"/)
  assert.match(preview, /\+ New/)
  assert.doesNotMatch(preview, /New map OR/)
  assert.doesNotMatch(preview, /logyq_handedness_v1/)
  assert.doesNotMatch(preview, /logiq_lab_pin_v1/)
  assert.doesNotMatch(preview, /logiq_v161_current_map_v1|logiq_v161_pending_save_v1/)
  for (const rpc of ['logiq_map_save', 'logiq_map_list', 'logiq_map_delete']) {
    assert.match(preview, new RegExp(rpc))
    assert.doesNotMatch(engine, new RegExp(rpc))
  }
  assert.doesNotMatch(engine, /logyq_saved_maps_v1/)
  assert.doesNotMatch(engine, /logyq_ashley_user_v1/)
  assert.doesNotMatch(engine, /savedMaps_v1/)
  assert.doesNotMatch(engine, /["']ashleyUser["']/)
  assert.doesNotMatch(engine, /function saveCurrentMap/)
  assert.doesNotMatch(engine, /function openMapsMenu/)
})

test('engine exposes a shared logyq API bag that fragments register onto', () => {
  const engine = engineSource()
  assert.match(engine, /const logyq = \{/)
  assert.match(engine, /function attach\(name, value\)/)
  assert.match(engine, /core: logyq/)
  for (const call of [
    "attach('config', CONFIG)",
    "attach('fly', CONFIG_FLY)",
    "attach('camera', {",
    "attach('state', state)",
    "attach('elements', elements)",
    "attach('utils', utils)",
    "attach('history', { pushHistory, undo, redo, autoFitSoon })",
    "attach('detectors', Detectors)",
    "attach('layout', {",
    "attach('structure', {",
    "attach('editing', {",
    "attach('selection', {",
    "attach('treeOps', {",
    "attach('deletion', {",
    "attach('wordDock', {",
    "attach('dock', {",
    "attach('input', {",
    "attach('mix', {",
    "attach('drag', dragManager)",
    "attach('treeManager', treeManager)",
    "attach('holdDrag', {",
    "attach('keyboard', {",
  ]) assert.ok(engine.includes(call), call)
  const config = readFileSync(join(logyqDir, 'js/engine/01-config.js'), 'utf8')
  const editing = readFileSync(join(logyqDir, 'js/engine/09-editing.js'), 'utf8')
  const selection = readFileSync(join(logyqDir, 'js/engine/10-selection.js'), 'utf8')
  assert.match(config, /const \{ elements, state \} = logyq/)
  assert.match(config, /const \{ state, moat \} = logyq/)
  assert.match(config, /attach\('camera', \{[\s\S]*?\}\);/)
  assert.match(config, /function flyCenterToUID/)
  assert.match(config, /function flyEditFocusToUID/)
  assert.match(config, /function phoneNoFollowCamera/)
  assert.match(config, /if \(phoneNoFollowCamera\(\)\) return;/)
  assert.match(config, /flyEditFocusToUID,/)
  assert.match(config, /phoneNoFollowCamera,/)
  assert.match(config, /function holdDragFrozen/)
  assert.match(config, /function holdDragBlocksBank/)
  assert.match(config, /window\.__logyqHoldDragFrozen = holdDragFrozen/)
  assert.match(config, /window\.__logyqHoldDragBlocksBank = holdDragBlocksBank/)
  assert.match(config, /v2-branch-drag/)
  assert.match(config, /__logyqHoldDragCommit/)
  assert.match(config, /__logyqHoldDragAllowBank/)
  assert.match(config, /__logyqHoldDragSession/)
  const apiBag = readFileSync(join(logyqDir, 'js/engine/00-api.js'), 'utf8')
  assert.match(apiBag, /holdDrag: null/)
  assert.match(config, /centerOnSelectedSoon\(120\)/)
  assert.doesNotMatch(config, /typeof centerOnSelectedSoon/)
  assert.match(editing, /attach\('editing'/)
  assert.match(selection, /attach\('selection'/)
  assert.match(selection, /function getSelectedUid/)
  const treeOps = readFileSync(join(logyqDir, 'js/engine/12-tree-ops.js'), 'utf8')
  assert.match(treeOps, /attach\('treeOps'/)
  assert.match(treeOps, /function addSiblingLeftOf/)
  assert.match(treeOps, /function insertParentAbove/)
  assert.match(treeOps, /logyq\.history\.pushHistory/)
  assert.match(treeOps, /logyq\.selection\.setSelected/)
  const deletion = readFileSync(join(logyqDir, 'js/engine/11-deletion.js'), 'utf8')
  assert.match(deletion, /attach\('deletion', \{[\s\S]*?\}\);/)
  assert.match(deletion, /const \{ state, utils \} = logyq/)
  assert.match(deletion, /logyq\.history\.pushHistory/)
  const layout = readFileSync(join(logyqDir, 'js/engine/07-layout-and-structure.js'), 'utf8')
  assert.match(layout, /attach\('layout', \{[\s\S]*?\}\);/)
  assert.match(layout, /attach\('structure', \{[\s\S]*?\}\);/)
  assert.match(layout, /const \{ state, config: CONFIG \} = logyq/)
  assert.match(layout, /logyq\.camera\.checkMoatAndAutoFit/)
  assert.doesNotMatch(layout, /typeof checkMoatAndAutoFit/)
  assert.doesNotMatch(layout, /function __swapWithinParent/)
  assert.doesNotMatch(layout, /function __reparentToAdjacentGroup/)
  assert.doesNotMatch(layout, /function __getSelectedUidSingle/)
  const detectors = readFileSync(join(logyqDir, 'js/engine/08-detectors.js'), 'utf8')
  assert.match(detectors, /logyq\.layout\.laneYForDepth/)
  assert.match(detectors, /logyq\.layout\.laneHeightForDepth/)
  assert.match(detectors, /function remapHoldDragGhostDrop/)
  assert.match(detectors, /v2-branch-drag/)
  assert.match(selection, /logyq\.layout\.laneYForDepth/)
  assert.match(selection, /logyq\.structure\.moveSelectedHorizontally/)
  assert.match(selection, /logyq\.structure\.moveSelectedVertically/)
  const treeManager = readFileSync(join(logyqDir, 'js/engine/16-tree-manager.js'), 'utf8')
  assert.match(treeManager, /logyq\.layout\.LabelWrap\.apply/)
  assert.match(treeManager, /logyq\.layout\.refreshLaneOnZoom/)
  assert.match(treeManager, /scaleExtent\(\[0\.02, 2\.4\]\)/)
  assert.doesNotMatch(treeManager, /scaleExtent\(\[0\.4, 2\.4\]\)/)
  assert.match(treeManager, /const content = 0\.9/)
  assert.match(treeManager, /const widthScale = \(usableW \* content\) \/ b\.width/)
  assert.match(treeManager, /const heightScale = \(usableH \* content\) \/ b\.height/)
  assert.match(treeManager, /logyq\.detectors\.build/)
  assert.match(treeManager, /logyq\.camera\.centerOnSelected/)
  assert.match(treeManager, /logyq\.camera\.checkMoatAndAutoFit/)
  assert.match(treeManager, /logyq\.keyboard\?\.keyDispatcher/)
  assert.match(treeManager, /logyq\.treeManager\.layoutAndRender/)
  assert.doesNotMatch(treeManager, /addEventListener\('keydown', keyDispatcher/)
  assert.doesNotMatch(treeManager, /function enforceMoatForSelected/)
  assert.doesNotMatch(treeManager, /function flyCenterToUID/)
  const wordDock = readFileSync(join(logyqDir, 'js/engine/14-word-dock.js'), 'utf8')
  assert.match(wordDock, /attach\('wordDock', \{[\s\S]*?\}\);/)
  assert.match(wordDock, /const \{ state, elements, utils \} = logyq/)
  assert.match(wordDock, /logyq\.elements\.svg\.on/)
  assert.match(treeOps, /logyq\.wordDock\.addWords/)
  assert.match(treeOps, /logyq\.wordDock\.render/)
  const history = readFileSync(join(logyqDir, 'js/engine/05-history.js'), 'utf8')
  assert.match(history, /logyq\.wordDock\.render/)
  assert.match(history, /logyq\.treeManager\.layoutAndRender/)
  assert.match(history, /logyq\.treeManager\.autoFit/)
  assert.doesNotMatch(history, /typeof treeManager/)
  const stateFrag = readFileSync(join(logyqDir, 'js/engine/02-state.js'), 'utf8')
  assert.match(stateFrag, /logyq\.wordDock\.addWords/)
  assert.match(stateFrag, /attach\('input', \{[\s\S]*?\}\);/)
  assert.match(stateFrag, /attach\('dock', \{[\s\S]*?\}\);/)
  assert.match(stateFrag, /function setSide/)
  assert.doesNotMatch(stateFrag, /function toggleVisibility/)
  assert.match(stateFrag, /logyq\.treeOps\.addChildOf/)
  assert.match(stateFrag, /logyq\.selection\.showToast/)
  assert.match(history, /logyq\.dock\.updateDockBounds/)
  const mix = readFileSync(join(logyqDir, 'js/engine/15-mix-and-context.js'), 'utf8')
  assert.match(mix, /attach\('mix', \{[\s\S]*?\}\);/)
  assert.match(mix, /const \{ state, utils \} = logyq/)
  assert.match(mix, /function mixCard/)
  assert.match(mix, /function cardLabel/)
  assert.match(mix, /if \(color\) node\.color = color/)
  assert.match(mix, /mixCard\(cardLabel\(n\.data\), n\.data\)/)
  assert.match(wordDock, /if \(typeof x\[key\] === 'string' && x\[key\]\.trim\(\)\) node\[key\] = x\[key\]/)
  assert.match(treeManager, /s\.close && s\.close\.addEventListener\('click', close\)/)
  assert.doesNotMatch(treeManager, /s\.showCarets/)
  assert.match(mix, /Contextmenu is never a Word Bank write/)
  assert.doesNotMatch(mix, /addWords\(/)
  assert.doesNotMatch(mix, /wordBank\.push/)
  assert.match(mix, /__logyqHoldDragBlocksBank/)
  assert.doesNotMatch(mix, /function onNodeLeftDown/)
  assert.doesNotMatch(mix, /function onNodeRightButtonDown/)
  assert.doesNotMatch(mix, /function flyToXY/)
  const keyboard = readFileSync(join(logyqDir, 'js/engine/17-keyboard.js'), 'utf8')
  assert.match(keyboard, /logyq\.wordDock\.clearChipSelection/)
  assert.match(keyboard, /logyq\.wordDock\.getSelectedChipNames/)
  assert.match(keyboard, /logyq\.mix\.randomizeTree/)
  assert.match(keyboard, /logyq\.camera\.centerOnSelected/)
  assert.match(keyboard, /logyq\.camera\.flyCenterToUID/)
  assert.doesNotMatch(keyboard, /window\.flyCenterToUID/)
  assert.doesNotMatch(keyboard, /window\.startInlineEdit/)
  assert.match(keyboard, /logyq\.dock\.cycleDockSide/)
  assert.match(keyboard, /logyq\.dock\.sideLabel/)
  assert.doesNotMatch(keyboard, /logyq\.dock\.toggleVisibility/)
  assert.doesNotMatch(keyboard, /function toggleDock/)
  assert.doesNotMatch(keyboard, /renderWordBank\?/)
  assert.doesNotMatch(keyboard, /renderTrash\?/)
  assert.match(editing, /logyq\.camera\.checkMoatAndAutoFit/)
  assert.match(treeManager, /logyq\.wordDock\.render/)
  assert.match(treeManager, /logyq\.mix\.randomizeTree/)
  assert.match(treeManager, /logyq\.mix\.onNodeContextMenu/)
  const bridge = readFileSync(join(logyqDir, 'js/engine/18-bridge.js'), 'utf8')
  assert.match(bridge, /treeOps\.addSiblingLeftOf/)
  assert.match(bridge, /treeOps\.insertParentAbove/)
  assert.doesNotMatch(bridge, /immediate: true/)
  assert.doesNotMatch(bridge, /snapLaidOutNodes/)
  assert.match(bridge, /if \(!label\) return false/)
  assert.match(bridge, /if \(uid == null \|\| String\(uid\) === ''\) return false/)
  assert.doesNotMatch(bridge, /explicitUid/)
  assert.doesNotMatch(bridge, /targetUid = explicitUid \? uid : logyq\.state\.selectedUid/)
  assert.match(bridge, /noEdit: true, select: true, rootAsChild: false/)
  assert.match(bridge, /createRelative\(direction, originUid\)/)
  assert.match(bridge, /if \(originUid == null \|\| String\(originUid\) === ''\) return null/)
  assert.doesNotMatch(bridge, /const origin = logyq\.state\.selectedUid/)
  assert.match(treeManager, /ensureUidLayout/)
  assert.match(treeManager, /syncCreateHitSlots/)
  assert.match(treeManager, /bindUidStamp/)
  assert.match(treeManager, /ensureCreateNodes/)
  assert.match(treeManager, /event\.__logyqUid/)
  assert.match(treeManager, /logyq-layout-settling/)
  assert.doesNotMatch(bridge, /addChildBelowSelectedAndEdit/)
  assert.match(bridge, /paintUid\(/)
  assert.match(bridge, /paintBranch\(/)
  assert.match(bridge, /item\.data\.color/)
  assert.match(bridge, /logyq\.wordDock\.render/)
  assert.match(bridge, /logyq\.mix\.randomizeTree/)
  assert.match(bridge, /logyq\.treeManager\.layoutAndRender/)
  assert.match(bridge, /logyq\.treeManager\.autoFit/)
  assert.match(bridge, /cycleDock\(\)/)
  assert.match(bridge, /setDockSide\(side\)/)
  assert.doesNotMatch(bridge, /treeManager\.layoutAndRender\.bind\(treeManager\)/)
  const drag = readFileSync(join(logyqDir, 'js/engine/13-drag.js'), 'utf8')
  assert.match(drag, /const \{ state, elements \} = logyq/)
  assert.match(drag, /logyq\.detectors\.pick/)
  assert.match(drag, /logyq\.selection\.insertNodeAtDrop/)
  assert.match(drag, /window\.DRAG_SLOP_PX \|\| 10/)
  assert.match(drag, /logyq\.input\.isTextField/)
  assert.match(drag, /if \(window\.__logyqHoldDragFrozen\?\.\(\)\)/)
  assert.match(drag, /dragManager\.clear\(\);/)
  assert.match(treeOps, /if \(window\.__logyqHoldDragFrozen\?\.\(\)\) return;/)
  assert.match(treeOps, /if \(window\.__logyqHoldDragBlocksBank\?\.\(\)\) return;/)
  assert.match(treeManager, /if \(window\.__logyqHoldDragFrozen\?\.\(\)\) return;/)
  assert.doesNotMatch(treeManager, /snapLaidOutNodes/)
  assert.match(treeManager, /syncHitSlots/)
  assert.match(treeManager, /g\.hit-slot/)
  assert.match(treeManager, /data-uid/)
  assert.match(treeManager, /requestCreateLayout/)
  assert.match(treeManager, /CREATE_SETTLE_MS: 260/)
  assert.match(treeManager, /layoutFlushQueued/)
  assert.match(treeOps, /function commitCreatedNode/)
  assert.match(treeOps, /requestCreateLayout/)
  assert.doesNotMatch(treeOps, /immediate: !!opts\.immediate/)
  assert.match(bridge, /if \(window\.__logyqHoldDragFrozen\?\.\(\)\) return;/)
  assert.match(wordDock, /typeof window !== 'undefined' && window\.__logyqHoldDragBlocksBank\?\.\(\)\) return;/)
  assert.match(keyboard, /logyq\.input\.isTextField/)
  assert.match(selection, /logyq\.input\.isTextField/)
  assert.match(treeManager, /logyq\.input\.isTextField/)
  assert.doesNotMatch(treeManager, /logyq\.dock\.cycleDockSide/)
  assert.match(treeManager, /logyq\.dock\.updateDockBounds/)
  assert.match(keyboard, /attach\('keyboard', \{[\s\S]*?\}\);/)
  assert.match(keyboard, /const \{ state, elements, utils \} = logyq/)
  assert.match(keyboard, /logyq\.editing\.openNodeEditor/)
  assert.match(keyboard, /logyq\.selection\.getSelectedUid/)
  assert.doesNotMatch(keyboard, /function getSelectedUid/)
  assert.match(keyboard, /function onRelativeCreateHotkeys/)
  assert.equal((keyboard.match(/addEventListener\('keydown'/g) || []).length, 1)
  assert.match(bridge, /logyq\.selection\.getSelectedUid/)
  assert.match(editing, /const \{ state, elements, config: CONFIG \} = logyq/)
  assert.match(selection, /const \{ state, elements \} = logyq/)
  assert.match(selection, /function onVHoldDown/)
  assert.match(selection, /function onGroupHotkeys/)
  assert.match(detectors, /const CONFIG = logyq\.config/)
  assert.match(history, /const \{ state, elements, config: CONFIG \} = logyq/)
  assert.match(editing, /setSelectionSet\(merged\)/)
  assert.doesNotMatch(engine, /function setSelectionSet/)
  assert.doesNotMatch(engine, /function startInlineEdit/)
  assert.doesNotMatch(engine, /function createFirstCardAndEdit/)
  assert.doesNotMatch(engine, /function getSelectionUids/)
  assert.doesNotMatch(engine, /function copySubtreeToClipboard/)
  assert.doesNotMatch(treeManager, /nEnter\.on\("dblclick"/)
  assert.doesNotMatch(treeManager, /lanePinBtn/)
  assert.doesNotMatch(layout, /function showLaneAtY/)
  assert.doesNotMatch(layout, /function hideLane/)
  assert.match(layout, /function refreshLaneOnZoom/)
  assert.doesNotMatch(keyboard, /window\.__addChildBelowSelectedAndEdit/)
  assert.doesNotMatch(stateFrag, /mapsBtn:/)
})

test('copied engine script parses', () => {
  assert.doesNotThrow(() => new Function(engineSource()))
  assert.ok(statSync(join(logyqDir, 'logos/LOGO_GREEN_Q.svg')).isFile())
})

test('theme styles live in the extracted stylesheet', () => {
  const html = readFileSync(indexPath, 'utf8')
  const css = readFileSync(join(logyqDir, 'css/app.css'), 'utf8')
  assert.match(html, /href="\/logyq\/css\/app\.css"/)
  assert.match(html, /<style id="logyq-phone-boot">/)
  assert.doesNotMatch(html.replace(/<style id="logyq-phone-boot">[\s\S]*?<\/style>/, ''), /<style>/)
  for (const marker of ['#trash', '#Dock', 'g.node', '.global-no-cursor', '--card-color']) {
    assert.ok(css.includes(marker), `missing css marker: ${marker}`)
  }
})

test('engine fragments concatenate to the served IIFE without edits', () => {
  const assembled = assembleLogyqEngine()
  assert.equal(assembled.names.length, 21)
  assert.deepEqual(assembled.names[0], '00-iife-open.js')
  assert.deepEqual(assembled.names[1], '00-api.js')
  assert.deepEqual(assembled.names.at(-1), '19-iife-close.js')
  assert.equal(assembled.source, engineSource())
  assert.match(assembled.source, /bindUidStamp/)
  assert.match(assembled.source, /logyq-layout-settling/)
  for (const name of [
    '00-api.js', '01-config.js', '03-utils.js', '05-history.js', '08-detectors.js',
    '10-selection.js', '13-drag.js', '16-tree-manager.js', '17-keyboard.js', '18-bridge.js',
  ]) assert.ok(assembled.names.includes(name), name)
})

test('preview fragments concatenate to the served enhancement without edits', () => {
  const assembled = assembleLogyqPreview()
  assert.deepEqual(assembled.names, [
    '00-boot.js', '01-helpers.js', '02-styles.js', '03-ui.js', '04-gestures.js',
    '05-v162-gestures.js', '06-persistence.js', '07-curriculum.js', '08-thekonym.js',
    '10-game.js', '09-folders.js',
  ])
  assert.equal(assembled.source, readFileSync(previewPath, 'utf8'))
  assert.ok(assembled.source.indexOf('const GAME_KEY') < assembled.source.lastIndexOf('})()'), 'game helpers stay inside the LOGYQ preview scope')
  assert.match(assembled.source, /function queueAutosave/)
  assert.match(assembled.source, /function planRemoteSync/)
  assert.match(assembled.source, /logyq-db-bubble/)
  assert.match(assembled.source, /reconcileBeforeSave/)
  assert.match(assembled.source, /function bootSession/)
  assert.match(assembled.source, /function encodeMapTree/)
  assert.match(assembled.source, /function isBlankDraft/)
  assert.match(assembled.source, /function abandonBlankDraft/)
  assert.match(assembled.source, /function openHomeLibrary/)
  assert.match(assembled.source, /createMap\(\{ edit: false \}\)/)
  assert.match(assembled.source, /editSelected\(\{ wipe: true, uid \}\)/)
  assert.match(assembled.source, /id="logyq-home-btn"/)
  assert.doesNotMatch(assembled.source, /New map OR/)
  assert.doesNotMatch(assembled.source, /createMap\(\{ edit: true \}\)/)
  assert.match(assembled.source, /function bindV162Gestures/)
  assert.match(assembled.source, /function injectStyles/)
  assert.match(assembled.source, /bridge\.cycleDock\(\)/)
  assert.doesNotMatch(assembled.source, /bridge\.dispatchKey\('w'\)/)
  assert.match(assembled.source, /window\.LOGYQPreview = preview/)
  assert.match(assembled.source, /attach\('gestures'/)
  assert.doesNotMatch(assembled.source, /logiq-spawn-puck/)
  assert.doesNotMatch(assembled.source, /function bindCanvasGestures/)
  assert.doesNotMatch(assembled.source, /function bindSpawnGestures/)
  assert.doesNotMatch(assembled.source, /logiq-mobile-context/)
  assert.doesNotMatch(assembled.source, /function updateContextActions/)
  assert.match(assembled.source, /HOLD_MS: 160/)
  assert.match(assembled.source, /DOUBLE_TAP_MS: 360/)
  assert.match(assembled.source, /FLICK_MIN: 52/)
  assert.match(assembled.source, /function edgePan/)
  assert.match(assembled.source, /function centerPanVector/)
  assert.match(assembled.source, /function clampPanToContent/)
  assert.match(assembled.source, /function beginCardPan/)
  assert.match(assembled.source, /function applyFingerPan/)
  assert.match(assembled.source, /function stopZoomGesture/)
  assert.match(assembled.source, /function classifyCardIntent/)
  assert.match(assembled.source, /function rankCardHits/)
  assert.match(assembled.source, /editSelected\(\{ uid \}\)/)
  assert.match(assembled.source, /createRelative\(direction, candidate\.uid\)/)
  assert.match(assembled.source, /editSelected\(\{ wipe: true, uid \}\)/)
  assert.match(assembled.source, /function hardClearBackground/)
  assert.match(assembled.source, /uidFromEvent/)
  assert.match(assembled.source, /uidFromTouchedNode/)
  assert.match(assembled.source, /uidFromVisualPoint/)
  assert.match(assembled.source, /hitEditUid/)
  assert.match(assembled.source, /hitLayoutSlot/)
  assert.match(assembled.source, /logyq-layout-settling/)
  assert.match(assembled.source, /!candidate\.moved && candidate\.uid/)
  assert.doesNotMatch(assembled.source, /snapLaidOutNodes/)
  assert.doesNotMatch(assembled.source, /armBlankCardMic\(state\.mic, doc, createdUid\)/)
  assert.match(assembled.source, /__logyqSuppressZoom/)
  assert.match(assembled.source, /__logyqHoldArming/)
  assert.match(assembled.source, /PAN_DEAD_PX: 56/)
  assert.match(assembled.source, /PAN_STEP: 16/)
  assert.doesNotMatch(assembled.source, /EDGE_ZONE: 84/)
  assert.match(assembled.source, /function fingerOffset/)
  assert.match(assembled.source, /cloneNode\(true\)/)
  assert.match(assembled.source, /OFFSET_UP_CM: 1\.1/)
  assert.match(assembled.source, /function liftPx/)
  assert.doesNotMatch(assembled.source, /LATCH_MAP_SHIFT/)
  assert.doesNotMatch(assembled.source, /function shiftMapOnLatch/)
  assert.match(assembled.source, /BANK_DWELL_MS: 480/)
  assert.match(assembled.source, /STILL_PX: 16/)
  assert.match(assembled.source, /function dragMousePoint/)
  assert.match(assembled.source, /function activeDockKind/)
  assert.match(assembled.source, /function paintCloneCard/)
  assert.match(assembled.source, /function stampOriginGhost/)
  assert.match(assembled.source, /v2-branch-origin-ghost/)
  assert.match(assembled.source, /logyq_paint_color_v1/)
  assert.match(assembled.source, /function paintFlickDown/)
  assert.match(assembled.source, /bridge\.paintBranch/)
  assert.match(assembled.source, /bridge\.paintUid/)
  assert.match(assembled.source, /__logyqHoldDragCommit/)
  assert.match(assembled.source, /__logyqHoldDragSession/)
  assert.match(assembled.source, /__logyqHoldDragAllowBank/)
  assert.match(assembled.source, /const commitTree/)
  assert.match(assembled.source, /function endHoldDragSession/)
  assert.match(assembled.source, /addEventListener\('contextmenu'/)
  assert.doesNotMatch(assembled.source, /logyq_handedness_v1/)
})

test('this branch does not modify existing logiq-* files', () => {
  const names = execFileSync('git', ['diff', '--name-only', 'origin/main...HEAD'], { encoding: 'utf8' })
    .split('\n')
    .map((line) => line.trim())
    .filter(Boolean)
  const dirty = execFileSync('git', ['status', '--porcelain'], { encoding: 'utf8' })
  const touched = [
    ...names,
    ...dirty.split('\n').map((line) => line.slice(3).trim()),
  ].filter(Boolean)
  const forbidden = touched.filter((name) => /(^|\/)logiq/i.test(name) && !name.startsWith('public/logyq/'))
  assert.deepEqual(forbidden, [])
})
