import { useEffect, useMemo, useRef, useState } from 'react'
import { supabase } from '../lib/supabase'
import { startRecordingSession, type RecordingSession } from '../lib/voiceCapture'
import './concept-interaction-review.css'

type Row = { id:string; interaction_code:string; source_coordinate:string; target_coordinate:string; source_language:string|null; source_mode:string; target_language:string|null; target_mode:string; derived_command:string; technical_description:string; teacher_asker_does:string; teacher_asker_example:string|null; teacher_natural_prompt:string|null; student_responder_does:string; expected_response:string|null; usefulness:number|null; difficulty:number|null; prerequisites:string|null; notes:string|null; review_note:string|null; ashley_confidence:number }
type Props={pin:string;onExit:()=>void}
const filters=[['all','All'],['0','0'],['1','1'],['2','2'],['3','3'],['2+','2+']]
export function ConceptInteractionReview({pin,onExit}:Props){
 const [rows,setRows]=useState<Row[]>([]),[idx,setIdx]=useState(0),[filter,setFilter]=useState('0'),[note,setNote]=useState(''),[msg,setMsg]=useState(''),[recording,setRecording]=useState(false)
 const rec=useRef<RecordingSession|null>(null)
 useEffect(()=>{supabase.rpc('lab_concept_interaction_read',{pin}).then(({data,error})=>{if(error)setMsg(error.message);else setRows(data as Row[])})},[pin])
 const visible=useMemo(()=>rows.filter(r=>filter==='all'||filter==='2+'?filter==='all'||r.ashley_confidence>=2:String(r.ashley_confidence)===filter),[rows,filter])
 useEffect(()=>setIdx(i=>Math.min(i,Math.max(0,visible.length-1))),[visible.length])
 const row=visible[idx]
 useEffect(()=>setNote(row?.review_note||''),[row?.id])
 async function save(conf?:number,newNote?:string){if(!row)return;const {data,error}=await supabase.rpc('lab_concept_interaction_review',{pin,interaction_id:row.id,new_confidence:conf??null,new_note:newNote??null,set_note:newNote!==undefined});if(error){setMsg(error.message);return}setRows(rs=>rs.map(r=>r.id===row.id?data as Row:r));setMsg('Saved')}
 async function choose(n:number){await save(n);setTimeout(()=>setIdx(i=>Math.min(i+1,Math.max(0,visible.length-1))),0)}
 async function mic(){if(recording){const s=rec.current;if(!s)return;s.stop();setRecording(false);setMsg('Transcribing…');const blob=await s.blobPromise;const form=new FormData();form.append('audio',blob,'concept-note.webm');const res=await fetch('/api/transcribe',{method:'POST',headers:{'x-review-pin':pin},body:form});const out=await res.json();if(!res.ok){setMsg(out.error||'Transcription failed');return}const next=[note,out.text].filter(Boolean).join(' ').trim();setNote(next);await save(undefined,next);return}try{rec.current=await startRecordingSession();setRecording(true);setMsg('Recording — tap again to stop')}catch(e){setMsg(e instanceof Error?e.message:'Microphone failed')}}
 if(!row)return <main className="ci"><header><button onClick={onExit}>‹ Lab</button><b>Concept Interactions</b></header><div className="ci-empty">{rows.length?'No interactions in this filter.':'Loading…'} {msg}</div></main>
 return <main className="ci"><header><button onClick={onExit}>‹ Lab</button><b>Concept Interactions</b><span>{idx+1}/{visible.length}</span></header><nav>{filters.map(([v,l])=><button className={filter===v?'on':''} onClick={()=>{setFilter(v);setIdx(0)}} key={v}>{l}</button>)}</nav><section className="ci-card"><div className="ci-title"><strong>{row.interaction_code}</strong><span>{row.derived_command}</span></div><div className="ci-flow"><div><small>SOURCE</small><b>{row.source_coordinate}</b><span>{row.source_language||'—'} · {row.source_mode}</span><em>Asker {row.teacher_asker_does}</em></div><div className="ci-dash">—</div><div><small>TARGET</small><b>{row.target_coordinate}</b><span>{row.target_language||'—'} · {row.target_mode}</span><em>Responder {row.student_responder_does}</em></div></div><p className="ci-tech">{row.technical_description}</p><div className="ci-example"><span><small>ASKER EXAMPLE</small>{row.teacher_asker_example||'Not proposed yet'}</span><span><small>NATURAL PROMPT</small>{row.teacher_natural_prompt||'Not proposed yet'}</span><span><small>EXPECTED</small>{row.expected_response||'Not proposed yet'}</span></div><div className="ci-meta"><span>Usefulness <b>{row.usefulness??'—'}</b></span><span>Difficulty <b>{row.difficulty??'—'}</b></span><span>Prerequisites <b>{row.prerequisites||'TBD'}</b></span></div><textarea value={note} onChange={e=>setNote(e.target.value)} onBlur={()=>save(undefined,note)} placeholder="Ashley note…"/><div className="ci-actions"><button className={recording?'rec':''} onClick={mic}>● Mic</button><div className="confidence"><small>ASHLEY CONFIDENCE</small>{[0,1,2,3].map(n=><button className={row.ashley_confidence===n?'selected':''} onClick={()=>choose(n)} key={n}>{n}</button>)}</div></div></section><footer><button onClick={()=>setIdx(i=>Math.max(0,i-1))}>‹</button><span>{msg||`${rows.filter(r=>r.ashley_confidence===0).length} unconfirmed`}</span><button onClick={()=>setIdx(i=>Math.min(visible.length-1,i+1))}>›</button></footer></main>
}
